name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # This is required for creating releases

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build
        run: |
          mkdir -p dist
          # Build for both Intel and Apple Silicon
          GOOS=darwin GOARCH=amd64 go build -o dist/touchymcrootface-darwin-amd64 ./cmd/touchymcrootface
          GOOS=darwin GOARCH=arm64 go build -o dist/touchymcrootface-darwin-arm64 ./cmd/touchymcrootface
          # Make executables
          chmod +x dist/*
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/touchymcrootface-darwin-amd64
            dist/touchymcrootface-darwin-arm64
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
