name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build
        run: |
          # Build for both Intel and Apple Silicon
          GOOS=darwin GOARCH=amd64 go build -o dist/touchid-setup-darwin-amd64 ./cmd/touchid-setup
          GOOS=darwin GOARCH=arm64 go build -o dist/touchid-setup-darwin-arm64 ./cmd/touchid-setup
          # Make executables
          chmod +x dist/*
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/touchid-setup-darwin-amd64
            dist/touchid-setup-darwin-arm64
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
